@baseUrl = http://localhost:3003/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB1YmxpY191c2VyIiwiaWQiOiI2NWE0YzU1ZjA3OWQwNTY1ODAwZDU3OTQiLCJpYXQiOjE3MDYxNjUxNjR9.wg5A6y0jrm1VToFk-DCxJUoDjjR0HCnP1P9EH9HukIw
@listId = 6594746da97bc8b7ccf2e844
@task1 = { "taskName": "blood test", "dueDate": "2023-12-09", "listName": "magic", "completed": false, "taskNote": ""}
@task2 = { "taskName": "stop taking tablets", "dueDate": "2023-12-24", "listName": "health", "completed": false, "taskNote": "stop before Dec 24"}
@task3 = { "taskName": "strri exercise", "dueDate": "2023-12-31", "listName": "health", "completed": false, "taskNote": "exercise more for health"}
@task4 = { "taskName": "drink more water", "dueDate": "2023-1-1", "listName": "health", "completed": false, "taskNote": "drink more water and stand up more"}

# users ---------------------------------------------------------------
### get all users
get http://localhost:3003/api/user

### Sign up
post http://localhost:3003/api/user/signup
Content-Type: application/json

{
  "username": "public_user",
  "password": "password"
}

### Log in
post http://localhost:3003/api/user/login
Content-Type: application/json

{
  "username": "public_user",
  "password": "pass"
}

### delete a user
delete {{baseUrl}}/user/659460e8c5a4229c54996055


# lists ---------------------------------------------------------------

### Get all lists
get {{baseUrl}}/lists
Content-Type: application/json
Authorization: bearer {{token}}

### Get a list
get {{baseUrl}}/lists/65886ff131f3041dad4f32f1
Content-Type: application/json
Authorization: bearer {{token}}

### Create new list
post {{baseUrl}}/lists
Content-Type: application/json
Authorization: bearer {{token}}

{
  "listName": "health"
}

### delete a list
delete {{baseUrl}}/lists/{{listId}}
Content-Type: application/json
Authorization: bearer {{token}}

### delete all lists
delete {{baseUrl}}/lists
Content-Type: application/json
Authorization: bearer {{token}}

# tasks ---------------------------------------------------------------
### get all tasks
get {{baseUrl}}/tasks
Content-Type: application/json
Authorization: bearer {{token}}


### create a new task
post {{baseUrl}}/tasks
Content-Type: application/json
Authorization: bearer {{token}}

{{task1}}

### update a task
put {{baseUrl}}/tasks
Content-Type: application/json
Authorization: bearer {{token}}

{{task4}}

### delete a task
delete {{baseUrl}}/tasks/6588755be563e2deb8d5fa11
Content-Type: application/json
Authorization: bearer {{token}}


### delete all tasks
delete {{baseUrl}}/tasks
Content-Type: application/json
Authorization: bearer {{token}}

# reset: clear and seed db ---------------------------------------------------------------
### reset db (clear + seed)
post {{baseUrl}}/testing/reset

### clear db
post {{baseUrl}}/testing/clear

### seed db
post {{baseUrl}}/testing/seed